name: Zip
on:
  create:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Zip folder
      run: cd .. && zip -r ${{ github.event.repository.name }}/${{ github.event.repository.name }}-${{ steps.tag.outputs.tag }}.zip ${{ github.event.repository.name }} -x "${{ github.event.repository.name }}/.git/*" "${{ github.event.repository.name }}/.github/*"
    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.event.repository.name }}-${{ steps.tag.outputs.tag }}.zip
        asset_name: ${{ github.event.repository.name }}-${{ steps.tag.outputs.tag }}.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"

