name: Zip
#on:
#  create:
#    tags:
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Zip Folder
      run: cd .. && zip -r ${{ github.event.repository.name }}/releases/${{ github.event.repository.name }}-latest.zip ${{ github.event.repository.name }} -x "${{ github.event.repository.name }}/.git/*" "${{ github.event.repository.name }}/.github/*" "${{ github.event.repository.name }}/releases/*"
    - name: Commit 
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Generate release"
        git push
